version: "2"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000"
    volumes:
      - ./:/usr/app
    external_links:
      - mysql_srv
    environment:
        DB_DATABASE: docfy
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_HOST: mysql_srv
        DB_CONNECTION: mysql
        VIRTUAL_HOST: docfy.server.localhost
        VIRTUAL_PORT: 3000
networks:
  default:
    external:
      name: server_default
